name: Build and Publish Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      # begin logins  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # end logins
      
      #https://github.com/docker/build-push-action/blob/master/docs/advanced/copy-between-registries.md
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            robwiederstein/econdash:latest
      # ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
            
      - name: Push to Docker Hub Registry
        run: |
            docker push robwiederstein/econdash:latest
