# R action templates can be found at https://github.com/r-lib/actions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: primary-workflow

jobs:
  primary-workflow:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    steps:
    
      # see https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v2
      
      # see https://github.com/r-lib/actions/tree/master/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
        run: Rscript -e 'print("R setup")'
      
      # see https://github.com/r-lib/actions/tree/master/setup-r-dependencies
      # install packages listed in DESCRIPTION
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck
        run: Rscript -e 'print("dependencies installed")'
          
      # see https://github.com/r-lib/actions/tree/master/check-r-package
      - name:  R CMD check 
        uses: r-lib/actions/check-r-package@v1
        run: Rscript -e 'print("cmd check passed")'

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      # see https://github.com/actions/upload-artifact
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
