name:  update_data

on:
  #schedule:
  #  - cron: "50 0 * * 1-7"
  push:
    branches: [main, master]

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v1
      - run: |
          Rscript -e 'source("data-raw/fetch_datasets.R")'
          Rscript -e 'devtools::build()'
